twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        images: '%images_url%'
        petites_images: '%images_url%/petites_images/'
        moyennes_images: '%images_url%/'
        grandes_images: '%images_url%/grandes_images/'
        fichiers: '%files_url%/'
        
